apiVersion: v1
kind: Service
metadata:
  name: azure-blob-proxy
  namespace: default
  labels:
    app.kubernetes.io/name: azure-blob-proxy
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: azure-blob-proxy
