name: docker

on:
  workflow_call:
    inputs:
      push:
        description: Push or not image to registry
        required: true
        type: boolean
      tag:
        description: Docker image tag
        required: true
        type: string
      latest:
        description: Add latest tag to docker image
        required: false
        type: boolean
        default: false


defaults:
  run:
    shell: bash -euo pipefail {0}

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.NEON_DOCKERHUB_USERNAME }}
          password: ${{ secrets.NEON_DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ inputs.push }}
          tags: neondatabase/azure-blob-proxy:${{ inputs.tag }}

      - name: Add latest tag to image
        if: inputs.latest
        run: docker buildx imagetools create -t 
                neondatabase/azure-blob-proxy:latest \
                neondatabase/azure-blob-proxy:${{ inputs.tag }}
