name: build

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash -euo pipefail {0}

jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: go build

  docker-build:
    needs: [lint, build]
    uses: ./.github/workflows/_docker.yml
    with:
      push: ${{ github.ref == 'refs/heads/main' }}
      tag: dev
    secrets: inherit
